language: csharp

solution: Logbook.sln

mono:
  - latest

install:
  - nuget restore Logbook.sln

script:
  - xbuild /p:Configuration=Release /p:TargetFrameworkVersion="v4.5" /p:DebugSymbols=False Logbook.sln
